### ISSUE TITLE
Auto bump required version for release on migration

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/MarkdownMacro#53]
Let's update the release action to auto increase the required version for migration. This way we don't have to maintain this going forward.

```curl --request PUT \
  --url 'https://marketplace.atlassian.com/rest/2/addons/com.atlassian.plugins.confluence.markdown.confluence-markdown-macro/migration' \
  --user '<USERNAME>:<APIKEY>' \
  --header 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"cloudMigrationAssistantCompatibility":"<version>"}'
```

**Comment by nhan-nguyen-se** [comment]
I think the required version for migration should only be updated when needed. How about create a properties file with content is something like:
- `migration.minimum-compatible-version=1.0.0`

Every time we make migration-related change and it does not backward compatible, then we update that property. The release action will read that value and make an update on marketplace.

**Comment by nhan-nguyen-se** [comment]
We also need to config the API key as a GitHub organization-wide secret. For the username do we need to config it as secret as well?

**Comment by bberenberg** [comment]
We can likely use the devops user and api key, and adjust it's permissions in marketplace.

I don't think we need to keep the version coded to a minimum, thats my point. We want to simplify support and testing for ourselves. 

The downside of this is that it could mean a customer on an old version of Confluence would have to upgrade Confluence to get a version of this app which has dropped deprecated APIs. 🤷

**Comment by nhan-nguyen-se** [comment]
@bberenberg Just created a PR. It will look for a token with name `MARKETPLACE_TOKEN` for user `devops@atlasauthority.com`. So I need your help on setup that secret. Basically it is two steps:
- grant marketplace access for `devops@atlasauthority.com` and generate a token for it
- register the generated token as a Github organization-wide secret with name `MARKETPLACE_TOKEN`

**Comment by bberenberg** [comment]
Why are we doing org wide? So we can re-use in other projects?

**Comment by nhan-nguyen-se** [comment]
Yes. For tableau for example.

According to this https://developer.atlassian.com/platform/marketplace/rest/v2/api-group-migrations/#api-addons-addonkey-migration-put PUT is for when create and PATCH is when update.

Also I notice I forgot to specify the new app version. Working on that.

**Comment by nhan-nguyen-se** [comment]
@bberenberg Have you tried the PATCH before and noticed it does not work?

**Comment by nhan-nguyen-se** [comment]
Just checked our marketplace info by calling this request:
```
https://marketplace.atlassian.com/rest/2/addons/com.atlassian.plugins.confluence.markdown.confluence-markdown-macro/migration
```

And got this response:
```
{
   "vendorId":1212980,
   "addonKey":"com.atlassian.plugins.confluence.markdown.confluence-markdown-macro",
   "addonName":"Markdown Macro for Confluence",
   "cloudMigrationAssistantCompatibility":"1.6.11"
}
```

I notice that from the response:
- `cloudMigrationAssistantCompatibility` has been updated to `1.6.11`
- It has less information than before. I did that request a few days ago and I'm pretty sure the response I got had more field than current one.

So I guess the marketplace info has been updated recently with PUT request, and PUT request will replace the old one. I'm not sure what is the impact of overwriting marketplace info.

**Comment by bberenberg** [comment]
Shoot, I probably screwed that up while testing. Do you happen to know what it used to show before?

**Comment by nhan-nguyen-se** [comment]
Unfortunately no. There was many fields and I don't remember the content.

**Comment by nhan-nguyen-se** [comment]
@bberenberg Just found this in my command line history:

```
debt@Stevens-MacBook-Pro Workspace % curl --request GET \
  --url 'https://marketplace.atlassian.com/rest/2/addons/com.atlassian.plugins.confluence.markdown.confluence-markdown-macro/migration' \
  --header 'Accept: application/json'
{"vendorId":1212980,"addonKey":"com.atlassian.plugins.confluence.markdown.confluence-markdown-macro","addonName":"Markdown Macro for Confluence","cloudAddonKey":"com.atlassian.plugins.confluence.markdown.confluence-markdown-macro","featureDifferenceDocumentation":"https://atlasauthority.atlassian.net/wiki/spaces/MARKDOWNCLOUD/pages/2666233923/Markdown+Macro+for+Confluence+-+Differences+in+Cloud+version","migrationDocumentation":"https://atlasauthority.atlassian.net/wiki/spaces/MARKDOWNCLOUD/pages/2666135581/Markdown+Macro+for+Confluence+-+Cloud+Migration","cloudMigrationAssistantCompatibility":"1.6.4"}% 
```

**Comment by bberenberg** [comment]
@nhan-nguyen-se woohoo! Can you put that back in place?

**Comment by nhan-nguyen-se** [comment]
@bberenberg I don't have permission to update marketplace info.

**Comment by bberenberg** [comment]
Ok i think i fixed it. Let's re-run the action here and confirm it works as expected?

**Comment by nhan-nguyen-se** [comment]
<img width="1638" alt="Screen Shot 2022-02-01 at 21 24 15" src="https://user-images.githubusercontent.com/39516534/151986079-118f9b0b-3607-4236-ad45-b46c13f4dfdb.png">

@bberenberg Field `cloudAddonKey` is still missing. Here is the value:

```
"cloudAddonKey":"com.atlassian.plugins.confluence.markdown.confluence-markdown-macro"
```

**Comment by bberenberg** [comment]
Good catch, fixed.

**Comment by nhan-nguyen-se** [comment]
Verified. The marketplace info is OK now.

**Comment by bberenberg** [comment]
And is it still ok after we run the automation?

**Comment by nhan-nguyen-se** [comment]
Yes. Release action is using PATCH request and only update `cloudMigrationAssistantCompatibility` field and leave all other fields untouched.
